### ISSUE TITLE
  ❤️  shows as :heart:ï¸ 

### ISSUE THREAD

**Issue by kaushikpatel1396** [safx/emoji-swift#9]
I Entered text as - Spread love and happiness ❤️ 

When escaped - Spread love and happiness : heart : ï¸
When unescaped - Spread love and happiness :heart: ï¸

Why does it adds ï. at the end of some emojis.

**Comment by SergeyPetrachkov** [comment]
Hi @pareekkhushboo77 , i've been playing with the pod and found that there is a problem with some of the emojis given in emojis dictionary. Numbers and heart and ,people say, about 60 more emojis have variation selector that prevents this lib from parsing emojis correctly.
See kindly attached the link:
https://github.com/mathiasbynens/emoji-regex/issues/3

**Comment by safx** [comment]
Sorry about the lazy reply.
As @SergeyPetrachkov mentioned above, this is caused by VARIATION SELECTOR-16 (U+FE0F).
I'll try to fix this, but I don't know how many emojis have variations at this time.

If you want to fix right now, please use custom emoji like this:
```swift
var emojiDictionary = String.emojiDictionary
emojiDictionary["heart_alt"] = "\u{2764}\u{fe0f}"
String.emojiDictionary = emojiDictionary
```

EDIT: I've found emoji variations at http://unicode.org/Public/emoji/5.0/emoji-variation-sequences.txt
